### PR TITLE
Using RateLimiter from Guava to avoid triggering GitHub abuse detection mechanism

### PR DESCRIPTION
**Pull request by bguerin**
Fix for #17, #28 and #88

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks.

**Comment by kevinsawicki** [comment]
I just deployed a `0.12.0` release with this fix in it, thanks :+1:

**Comment by bguerin** [comment]
Great, thanks !

**Comment by mjremijan** [comment]
Small tip, use --debug when running Maven.  I thought I ran into the #101 problem but it just took a while to generate the large number of blobs.  Running with --debug showed the progress

**Comment by alessandro-molari** [comment]
I'm facing the same problem (using version `0.12`).

To create 460 blobs it takes like 1 hour (not joking).

**Comment by jakeswenson** [comment]
Yes sadly this PR didn't take GHE in to account at all, and there is no way to override this setting... even though there  is no way i can exceed my GHE rate limit....

**Comment by bguerin** [comment]
@jakeswenson GHE ?

**Comment by jakeswenson** [comment]
@bguerin GHE = Github Enterprise
Basically a corporate github solution

**Comment by bguerin** [comment]
@jakeswenson ok thanks. How does GHE works ? Higher limit, no limit at all ?

**Pull request merged**
